services:
  - type: web
    name: bittu-study-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: PORT
        value: 10000
