```python
# Feature configuration
ENABLE_ANALYTICS = True
ENABLE_AI = True
ENABLE_EXPORT = True
ENABLE_SEARCH = True
ENABLE_REMINDERS = True
ENABLE_FLASHCARDS = True
ENABLE_SPACED_REPETITION = True
ENABLE_WEB_DASHBOARD = True 
